### ISSUE TITLE
plz modified docker-compose.yml

### ISSUE THREAD

**Issue by cjinzy** [Monogramm/docker-wordpress#6]
version: '2'

volumes:
    wordpress_html:
    wordpress_db:

service:
    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
            - wordpress_db:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD="
            - "MYSQL_PASSWORD="
            - "MYSQL_DATABASE=wordpress"
            - "MYSQL_USER=wordpress"

    wordpress:
        image: monogramm/docker-wordpress
        restart: always
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        environment:
            - "WORDPRESS_DB_HOST=mariadb"
            - "WORDPRESS_DB_NAME=wordpress"
            - "WORDPRESS_DB_USER=wordpress"
            - "WORDPRESS_DB_PASSWORD="
        volumes:
            - wordpress_html:/var/www/html

**Comment by madmath03** [comment]
Hello,

You will have to give a little more information and write something about this docker-compose...

**Comment by cjinzy** [comment]
I tried to use your example.

The following error occurred.

The error found that this was wrong.

> Invalid top-level property "mariadb". Valid top-level sections for this Compose file are: services, version, networks, volumes, and extensions starting with "x-".

That means there should be `service:` at the top level of `maraidb`.

So I want to change it as below.

`version: '2'

volumes:
    wordpress_html:
    wordpress_db:

service:
    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
        - wordpress_db:/var/lib/mysql
        environment:
        - "MYSQL_ROOT_PASSWORD="
        - "MYSQL_PASSWORD="
        - "MYSQL_DATABASE=wordpress"
        - "MYSQL_USER=wordpress"

    wordpress:
        image: monogramm/docker-wordpress
        restart: always
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        environment:
            - "WORDPRESS_DB_HOST=mariadb"
            - "WORDPRESS_DB_NAME=wordpress"
            - "WORDPRESS_DB_USER=wordpress"
            - "WORDPRESS_DB_PASSWORD="
        volumes:
            - wordpress_html:/var/www/html
`

**Comment by cjinzy** [comment]
I'm sorry.
I made a mistake mark down.
So rewrite it.
```
version:` '2'

volumes:
    wordpress_html:
    wordpress_db:

service:
    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
        - wordpress_db:/var/lib/mysql
        environment:
        - "MYSQL_ROOT_PASSWORD="
        - "MYSQL_PASSWORD="
        - "MYSQL_DATABASE=wordpress"
        - "MYSQL_USER=wordpress"

    wordpress:
        image: monogramm/docker-wordpress
        restart: always
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        environment:
            - "WORDPRESS_DB_HOST=mariadb"
            - "WORDPRESS_DB_NAME=wordpress"
            - "WORDPRESS_DB_USER=wordpress"
            - "WORDPRESS_DB_PASSWORD="
        volumes:
            - wordpress_html:/var/www/html
```
